CREATE TABLE IF NOT EXISTS posts(
	id VARCHAR(8) PRIMARY KEY,
	author VARCHAR(20) NOT NULL,
	title VARCHAR (300) NOT NULL,
	score SMALLINT NOT NULL,
	comments SMALLINT UNSIGNED NOT NULL,
	created_utc INT UNSIGNED NOT NULL,
	updated_utc INT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS tags(
	tag VARCHAR(64) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS post_tags(
	post VARCHAR(8) NOT NULL,
	tag VARCHAR(64) NOT NULL,
	PRIMARY KEY(post, tag),
	FOREIGN KEY(post) REFERENCES posts(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(tag) REFERENCES tags(tag)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
	username VARCHAR(20) PRIMARY KEY,
	password VARCHAR(64) NOT NULL,
	reddit_username VARCHAR(20),
	role SMALLINT UNSIGNED DEFAULT 0
);